### ISSUE TITLE
make a basic The Cannon landing page

### ISSUE THREAD

**Issue by davidwhogg** [andycasey/AnniesLasso#6]
This should have
- license rider that says cite Ness et al and Casey et al in prep
- list of projects that we want to do, with a few sentences about each
- list of example projects that have used TheCannon

@mkness and @davidwhogg can help write the second two items.

**Comment by davidwhogg** [comment]
ps. Should be exposed on github so it is easy for us to edit and take pull requests.

**Comment by andycasey** [comment]
I think we could probably do this pretty effectively with [GitHub Pages](https://pages.github.com/), then re-route thecannon.io to the GH Pages front. We could include project pages, etc, and then just link to the documentation (on readthedocs.org) from the GH pages design. We should be able to just commit changes to a `gh-pages` branch on this repository in order to make changes to the project page.

Any objections?

**Comment by davidwhogg** [comment]
None here.  Do it.
